### ISSUE TITLE
Query parameters not working?

### ISSUE THREAD

**Issue by aarnej** [maximilianhurl/bravado-django-test-client#6]
In there are parameters in a GET operation with the "in: query" specifier, they don't seem to be currently passed on to Django as query parameters. Maybe I have misunderstood something but for me the fix was to change DjangoTestFutureAdapter from this:
```
# convert data from a string to json
data = request.get("data", None)
if data:
    data = json.loads(data)
```
to this:
```
 if request['method'].lower() == 'get':   
     data = request.get('params', None)   
 else:                                    
     # convert data from a string to json 
     data = request.get("data", None)     
     if data:                             
         data = json.loads(data)          
```
The spec I have looks roughly like this:
```
  /objects/:
    get:
      ...
      parameters:
        - name: "identifier"
          in: query
          required: true
          type: string
```
and in  the test case I use it something like this:
```
objects = client.objects.get_objects( 
    identifier='X'                              
).result()                                              
```
